app/cyclab/urls.py
from django.urls import path, include, register_converter
from django.contrib import admin
from .routers import router

from .views import admin as admin_views
from .views import osm as osm_views
from .views import static as static_views
from .views import user as user_views

from cyclab.converts import FloatUrlParameterConverter

register_converter(FloatUrlParameterConverter, 'float')

urlpatterns = [
    path('', static_views.index, name='index'),
    path('export/segments-notes.csv', static_views.export_segments_notes_csv, name='export_csv'),
    path('export/', static_views.export_page, name='export'),
    path('bboxcyclabsegments/', osm_views.bbox_segments,
        name='bbox_cyclab_segments'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', user_views.logout_view, name='logout'),
    path('login/', user_views.json_login, name='login'),
    path('user/<int:user_id>/',
        user_views.user_detail, name='user_detail'),
    path('register/', user_views.register_view, name='register'),
    path(
        'register/registration-success/',
        user_views.registration_success, name='registration_success'),
    path('register/email/validation/<slug:uidb64>/<slug:token>/',
        user_views.email_validation, name='email_validation'),
    path('api-auth/', include('rest_framework.urls')),
    path('help/index.html', static_views.help_page, name='help'),
    path('help/about.html', static_views.about, name='about'),
    path('help/data.html', static_views.data, name='data'),
    path('api/', include(router.urls)),
    path(
        'admin/vote-transfer/<int:deleted_segment_id>/',
        admin_views.vote_transfer, name='vote_transfer'),
    path(
        'admin/vote-transfer/<int:deleted_segment_id>/handle',
        admin_views.handle_vote_transfer, name='handle_vote_transfer'),
    path(
        'admin/set-in-frigo/<int:deleted_segment_id>/',
        admin_views.set_in_frigo, name='vote_in_frigo'),
    path('admin/step1_clean_trivial_transfer_tables/<float:new_buffer_size>/<float:del_buffer_size>/<int:seg_in_buffer>/',
        admin_views.step1_clean_trivial_transfer_tables, name='step1_clean_trivial_transfer_tables'
    ),
    path('admin/step2_generate_cyclab_segments_l93_table',
        admin_views.step2_generate_cyclab_segments_l93_table, name='step2_generate_cyclab_segments_l93_table'),
    path('admin/step3_generate_cyclab_segments_l93_index',
        admin_views.step3_generate_cyclab_segments_l93_index, name='step3_generate_cyclab_segments_l93_index'),
    path(
        'admin/prepare-trivial-transfer/<float:new_buffer_size>/<float:del_buffer_size>/<int:seg_in_buffer>/',
        admin_views.prepare_trivial_transfer, name='prepare_trivial_transfer'),
    path(
        'admin/check-trivial-transfer/',
        admin_views.check_trivial_transfer, name='check_trivial_transfer'),
    path(
        'admin/handle-trivial-transfer/<int:vote_nbr_to_handle>',
        admin_views.handle_trivial_transfer, name='handle_trivial_transfer'),
    path('admin/', admin.site.urls),
]

app/cyclab/models/user.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.mail import send_mail
from django.template.loader import get_template
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.conf import settings

import logging
logger = logging.getLogger(__name__)

class UserManager(BaseUserManager):
    def create_user(
            self, email, first_name, last_name, password=None,
            commit=True):
        """
        Creates and saves a User with the given email, first name, last name
        and password.
        """
        if not email:
            raise ValueError(_('Users must have an email address'))
        if not first_name:
            raise ValueError(_('Users must have a first name'))
        if not last_name:
            raise ValueError(_('Users must have a last name'))

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        if commit:
            user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        """
        Creates and saves a superuser with the given email, first name,
        last name and password.
        """
        user = self.create_user(
            email,
            password=password,
            first_name=first_name,
            last_name=last_name,
            commit=False,
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICES = (
        ('h', _('Male')),
        ('f', _('Female')),
    )

    email = models.EmailField(
        verbose_name=_('email address'), max_length=255, unique=True
    )
    # password field supplied by AbstractBaseUser
    # last_login field supplied by AbstractBaseUser
    username = models.CharField(max_length=200, blank=False, unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    birth_year = models.IntegerField(null=True, blank=True)
    is_expert = models.BooleanField(default=False)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True)
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'
        ),
    )
    # is_superuser field provided by PermissionsMixin
    # groups field provided by PermissionsMixin
    # user_permissions field provided by PermissionsMixin
    is_email_verified = models.BooleanField(default=False)

    date_joined = models.DateTimeField(
        _('date joined'), default=timezone.now
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = f'{self.first_name} {self.last_name}'
        return full_name.strip()

    def __str__(self):
        return f'{self.get_full_name()} <{self.email}>'

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

@receiver(post_save, sender=User)
def automatic_profile_creation(sender, instance, created, **kwargs):
    if created:
        profile = UserProfile(user=instance, rider_type=3, rapidity=4)
        profile.save()

@receiver(post_save, sender=User)
def send_email_check(sender, instance, created, **kwargs):
    user = instance
    logger.critical("before if condition")
    if created:
        logger.critical("send the email")

        context = {
            'user': user,
            'token':str(default_token_generator.make_token(user)),
            'uidb64': str(urlsafe_base64_encode(force_bytes(user.pk))),
            'url_base': settings.SITE_URL,
        }

        email_template = get_template('registration/email_activation.txt')
        email_content = email_template.render(context)

        send_mail(
            _('Please activate your account'),
            email_content,
            None,
            [user.email],
            fail_silently=False,
        )

class UserProfile(models.Model):
    RAPIDITY_CHOICES = (
        (0, _('Louveteau')),
        (1, _('Tortue')),
        (2, _('Champion'))
    )

    TYPE_CHOICES = (
        (0, _('Daily rider')),
        (1, _('Leasure rider'))
    )

    user = models.ForeignKey(
        User, related_name='profiles', on_delete=models.CASCADE)
    rider_type = models.SmallIntegerField(choices=TYPE_CHOICES, null=True)
    rapidity = models.SmallIntegerField(choices=RAPIDITY_CHOICES, null=True)
    is_active = models.BooleanField(default=True)

app/cyclab/views/city.py
from rest_framework import viewsets
from ..serializers.city import CitySerializer
from ..models import City

class CityViewSet(viewsets.ModelViewSet):
    queryset = City.objects.all()
    serializer_class = CitySerializer

app/cyclab/views/osm.py
from django.core.serializers import serialize
from django.contrib.gis.geos import Polygon
from django.http import JsonResponse

from rest_framework import viewsets
from rest_framework.exceptions import MethodNotAllowed

import json

from ..models.osm import Segments, SegmentsDeleted, Ways
from ..serializers.osm import SegmentsSerializer, SegmentsDeletedSerializer, \
    WaysSerializer

def bbox_segments(request):
    """Gets all the segments within a given bounding-box"""
    bbox_str = request.GET
    bbox_arr = bbox_str["bbox"].split(",")
    # pprint(bbox_arr) TODO REMOVE ?

    bbox_arr = map(lambda x: float(x), bbox_arr)
    bb_polygon = Polygon.from_bbox(bbox_arr)

    bbox_segments = Segments.objects.filter(geom__intersects=bb_polygon).exclude(vote_default=0)

    serialized_bbox_segments = serialize('geojson', bbox_segments, fields=(
        'pk', 'way', 'nodestart', 'nodeend', 'geom', 'vote_default', 'vote_number', 'vote_average'))
    bbox_segments_json = json.loads(serialized_bbox_segments)
    return JsonResponse(bbox_segments_json, safe=False)

# GET SEGMENT DETAIL


def segment_detail(request, segment_id):
    segment_id = int(segment_id)
    segment_detail = Segments.objects.filter(pk=segment_id)

    serialized_segm_detail = serialize('geojson', segment_detail, fields=(
        'pk', 'way', 'nodestart', 'nodeend', 'geom', 'vote_default', 'vote_number', 'vote_average'))

    segment_detail_json = json.loads(serialized_segm_detail)
    return JsonResponse(segment_detail_json, safe=False)


# Views generated using DRF
class SegmentsViewSet(viewsets.ModelViewSet):
    queryset = Segments.objects.all()
    serializer_class = SegmentsSerializer

class SegmentsDeletedViewSet(viewsets.ModelViewSet):
    queryset = SegmentsDeleted.objects.all()
    serializer_class = SegmentsDeletedSerializer

class WaysViewSet(viewsets.ModelViewSet):
    queryset = Ways.objects.all()
    serializer_class = WaysSerializer

    def list(self, request):
        """Deactivate list method (performance)"""
        raise MethodNotAllowed('GET', detail='Method "GET" not allowed without lookup')

app/cyclab/views/static.py
# Views for static elements of the site :
# - static web pages (help, about, ....)
# - export file (CSV GENERATED)
import logging
from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse

from ..models import City

logger = logging.getLogger(__name__)

def index(request):
    """Index page for the app"""
    cities = City.objects.all()
    return render(request, 'cyclab/main.html', {'cities': cities})

def help_page(request):
    return render(request, 'cyclab/help.html')

def about(request):
    return render(request, 'cyclab/about.html')

def data(request):
    return render(request, 'cyclab/data.html')

def export_page(request):
    return render(request, 'cyclab/export.html')

def export_segments_notes_csv(request):
    file_content = open('/app/cyclab/media/export/segments-notes.csv', 'rb')
    response = HttpResponse(content=file_content)
    response['Content-Type'] = 'text/csv'
    response['Content-Disposition'] = \
        f'attachment; filename="export_{datetime.now().strftime("%y%m%d-%H%M%S")}.csv"'
    return response

app/cyclab/views/user.py
# View associated to user account stuff (login, logout, ...)
import logging

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.utils.translation import gettext as _

from rest_framework import viewsets
from rest_framework.exceptions import MethodNotAllowed

from ..forms import RegisterForm, UserDetailForm
from ..models.user import User, UserProfile
from ..serializers.user import UserSerializer, ProfileSerializer

logger = logging.getLogger(__name__)

def json_login(request):
    if request.method == "POST":
        email = request.POST.get('username')
        password = request.POST.get('password')

        print(f"Email: {email}")
        print(f"Password: {password}")


        user = authenticate(request, email=email, password=password)

        if not user: # user is None :
            data = {
                'status_code': 401,
                'message': _('Username or password are incorrect, try again.')
            }
        elif not user.is_active:
            data = {
                'status_code': 401,
                'message': _('This account is no longer active')
            }
        elif not user.is_email_verified:
            data = {
                'status_code': 401,
                'message': _('You should activate your account using the link sent by email')
            }
        else:
            login(request, user)
            data = {
                'user': user.id,
                'status_code': 200,
                'message': _('You have successfully logged in')
            }
    else:
        form = AuthenticationForm()
        return render(request, 'registration/login.html', {'form': form})

    return JsonResponse(data)


def email_validation(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except User.DoesNotExist:
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        # default_token_generator are valid for 3 days see PASSWORD_RESET_TIMEOUT
        user.is_email_verified = True
        user.save()
        login(request, user)

        messages.success(request, _('Your account has been confirmed and you are now logged in'))

        return redirect(registration_success)
    else:
        messages.error(request, _('Activation link is invalid! Please contact us at info@droitauvelo.org'))
        return redirect(registration_success)

def logout_view(request):
    logout(request)
    return redirect('index')

def register_view(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, _('You have succesfully registered. Please confirm your account through the email that has been sent'))

            return redirect(registration_success)
        else:
            messages.error(request, "Error")
    else:
        form = RegisterForm()
    return render(request, 'registration/register.html', {'form': form})

def registration_success(request):

    return render(request, 'registration/registration-success.html')

def user_detail(request, user_id):

    if request.method == 'POST':
        form = UserDetailForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            messages.success(request, _('Your details have been succesfully modified'))
    else:
        form = UserDetailForm(instance = request.user)
    return render(request, 'cyclab/user_detail.html', {
            'user': request.user,
            'form': form
    })
class UserViewSet(viewsets.ModelViewSet):
    # TODO VERIFIER QUE ça pose pas problème si accès aux données users vi API (fuite de données)
    queryset = User.objects.all()
    serializer_class = UserSerializer

    def list(self, request):
        """Deactivate list method (security)"""
        raise MethodNotAllowed('GET', detail='Method "GET" not allowed without lookup')


class ProfileViewSet(viewsets.ModelViewSet):
    # TODO VERIFIER QUE ça pose pas problème si accès aux données users vi API (fuite de données)
    queryset = UserProfile.objects.all()
    serializer_class = ProfileSerializer

    def list(self, request):
        """Deactivate list method (security)"""
        raise MethodNotAllowed(
            'GET', detail='Method "GET" not allowed without lookup')

app/cyclab/views/votes.py
from rest_framework import viewsets
from rest_framework.exceptions import MethodNotAllowed

from ..models.votes import VoteSegment, VoteReason
from ..serializers.votes import VoteSerializer, VoteReasonSerializer

class VoteViewSet(viewsets.ModelViewSet):
    queryset = VoteSegment.objects.all()
    serializer_class = VoteSerializer

    def list(self, request):
        """Deactivate list method (performance)"""
        raise MethodNotAllowed('GET', detail='Method "GET" not allowed without lookup')

class VoteReasonViewSet(viewsets.ModelViewSet):
    queryset = VoteReason.objects.all()
    serializer_class = VoteReasonSerializer

app/cyclab/templates/cyclab/about.html
{% load i18n %}
<!doctype html>
<html>
    <head>
        {% load static %}
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <title>{% trans "About us" %} - Cyclabilité</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/help.css' %}"></link>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <div id="menu">
            <nav>
                <ul>
                <li>
                    <a href="index.html">
                        {% trans "Help" %}
                    </a>
                </li>
                <li>
                    <a href="data.html">
                        {% trans "Data" %}
                    </a>
                </li>
                <li>
                    <a href="about.html">
                        {% trans "About us" %}
                    </a>
                </li>
                </ul>
            </nav>
        </div>

        <div id="content">
            <p><a href="{% url 'index' %}">{% trans "Return to map" %}</a></p>
            <h1>{% trans "About us" %}</h1>
            <p>
                L'outil a été développé pour l'association
                <a href="http://www.droitauvelo.org/" target="_blank">Droit au vélo – ADAV</a>.
                Cette carte est financé par <b>Hauts de France Mobilité</b> dans le cadre de son projet de plateforme
                intermodale <a href="https://www.passpass.fr" target="_blank">Passpass.fr</a>. Elle a également été financé
                par le <b>Conseil Départemental du Nord</b> ainsi que par la <b>Communauté Urbaine de Dunkerque.</b>
            </p>
            <p>
                Cet outil a été développé par <a href="http://champs-libres.coop/" target="_blank">Champs-Libres</a>
                une société coopérative à finalité sociale qui crée des applications,
                fournit des géo-services et supporte le logiciel libre.
            </p>
            <p>
                L'outil est "open source". Le code source se trouve sur
                <a href="https://gitlab.com/cyclabilite" target="_blank">https://gitlab.com/cyclabilite</a>.
            </p>
        </div>
    </body>
</html>

app/cyclab/templates/cyclab/data.html
{% load i18n %}
<!doctype html>
<html>
    <head>
        {% load static %}
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <title>{% trans "Data" %} - Cyclabilité</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/help.css' %}"></link>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <div id="menu">
            <nav>
                <ul>
                <li>
                    <a href="index.html">
                        {% trans "Help" %}
                    </a>
                </li>
                <li>
                    <a href="data.html">
                        {% trans "Data" %}
                    </a>
                </li>
                <li>
                    <a href="about.html">
                        {% trans "About us" %}
                    </a>
                </li>
                </ul>
            </nav>
        </div>

        <div id="content">
            <p><a href="{% url 'index' %}">{% trans "Return to map" %}</a></p>
            <h1>{% trans "Data" %}</h1>
            <p>
                Un export quotidien des notes est disponible en fichier .csv :
                <br><br>
                <a href="https://cyclabilite.droitauvelo.org/export/" target="_blank">https://cyclabilite.droitauvelo.org/export/</a>
            </p>

            <p>
                Pour l'utiliser, il faut utiliser <b>le logiciel QGIS</b> et joindre ce fichier au réseau routier
                Openstreetmap format ESRI Shapefile, du
                <a href="https://download.geofabrik.de/europe/france/nord-pas-de-calais.html" target="_blank">Nord Pas-de-Calais</a>
                et de la <a href="https://download.geofabrik.de/europe/france/picardie.html" target="_blank">Picardie</a>, disponibles sur
                Geofabrik.
            </p>
            <p>
                N'hésitez surtout pas à nous <a href="https://www.champs-libres.coop/" target="_blank">contacter</a> afin de
                vous aider dans la récupération des données.
            </p>
        </div>
    </body>
</html>

app/cyclab/templates/cyclab/export.html
{% load i18n %}
<!doctype html>
<html>
    <head>
        {% load static %}
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <title>{% trans "Data" %} - Cyclabilité</title>
    </head>
    <body>
        <ul>
            <li><a href="{% url 'export_csv' %}">{% url 'export_csv' %}</a></href></li>
        </ul>
    </body>
</html>

app/cyclab/templates/cyclab/help.html
{% load i18n %}
<!doctype html>
<html>
    <head>
        {% load static %}
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <title>{% trans "Help" %} - Cyclabilité</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/help.css' %}"></link>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>

    <body>
        <div id="menu">
            <nav>
                <ul>
                <li>
                    <a href="index.html">
                        {% trans "Help" %}
                    </a>
                </li>
                <li>
                    <a href="data.html">
                        {% trans "Data" %}
                    </a>
                </li>
                <li>
                    <a href="about.html">
                        {% trans "About us" %}
                    </a>
                </li>
                </ul>
            </nav>
        </div>

        <div id="content">
            <p><a href="{% url 'index' %}">{% trans "Return to map" %}</a></p>

            <h1>{% trans "Help" %}</h1>

            <h2>Principe général</h2>

            <p>
                <b>La carte de cyclabilité</b> est une carte collaborative qui vous permet, en tant que cycliste, 
                de <b>noter votre ressenti sur la possibilité de circuler à vélo en sécurité</b> sur les voies 
                de la région. Son objectif est de représenter, le plus objectivement, la cyclabilité du territoire 
                et de <b>conseiller les cyclistes dans leur recherche d’itinéraire.</b>
            </p>

            <p>
                Les rues et routes « agréables » à vélo figurent en vert, tandis que les axes les plus dangereux
                figurent en rouge. Afin que tous les avis soient pris en compte, <b>une moyenne est calculée
                pour chaque voie.</b> Les données sont sous licence libre (OdBL).
            </p>

            <p>
                L’ensemble des notes permet d’alimenter <b>le calculateur d’itinéraire passpass.fr</b>, la
                plateforme régionale gérée par le syndicat mixte <i>Hauts-de-France Mobilité.</i> L’outil
                Passpass permet d’accompagner l’usager sur l’ensemble de sa chaîne de déplacements
                avec la possibilité de combiner les alternatives à l’usage de la voiture individuelle et
                passer indifféremment d’un opérateur de transport ou de mobilité à l’autre.
            </p>

            <h2>Les critères</h2>

            <p>
                <b>La cyclabilité d’une voie</b> dépend principalement de :

                <ul>
                <li> la qualité et la pertinence des <b>aménagements cyclables</b></li>
                <li> la densité et la vitesse du <b>trafic automobile</b></li>
                <li> la qualité du <b>revêtement de la voie</b></li>
                </ul>
            </p>

            <div class="mx-auto" style="width: 800px;">
                <img src="https://droitauvelo.org/local/cache-vignettes/L640xH339/rue_agreable_a_velo-448a9.jpg?1537295120" height="250" class="mx-auto" >
            </div>

            <p>
                <b>Sur ces critères, vous pouvez attrbuer une note globale, allant de 1 à 5 : </b>
            </p>

            <div class="mx-auto" style="width: 600px;">
                <img src="https://droitauvelo.org/IMG/jpg/legende_cyclabilite.jpg" height="200">
            </div>

            <h2>Créez votre compte...</h2>

            <ol>
                <li>
                <b>Choisisez votre identifiant</b> et saisissez vos adresse email et mot de passe.
                </li>
                <li>
                <b>Confirmez votre inscription</b>, en cliquant sur le lien, contenu dans l’email
                de confirmation d’inscription reçu en retour.
                </li>
                <li>
                Afin de connaître la pratique des contributeurs,
                <b>choissisez un ou plusieurs profils de cycliste</b> :
                <ul>
                    <li><b>Champion</b> (Vous roulez dans la circulation).</li>
                    <li><b>Tortue</b> (Vous évitez les axes à forte circulation).</li>
                    <li><b>Louveteau</b> (Vous circulez avec des enfants).</li>
                </ul>
                </li>
            </ol>

            <div class="mx-auto" style="width: 300px;">
                <img src="../../static/images/onglet_se_connecter.png" width="150" >
            <br><br>
                <img src="../../static/images/creer_un_compte.png" width="150" >
            </div>

            <h2>Et contribuez !</h2>

            <ol>
                <li><b>Cliquez sur la rue.</b></li>
                <li>
                Regardez les notes déja attribuées, puis
                <b>cliquez sur «Voter» afin d’ajouter la vôtre.</b>
                </li>
                <li>
                Choisissez également <b>votre profil de
                cycliste,</b> ainsi que <b>le sens de circulation.</b>
                </li>
            </ol>

            <div class="mx-auto" style="width: 300px;">
                <img src="../../static/images/capture_note.jpeg" height="250" >
            </div>



            <p>
                <b>Pour aller plus loin</b> :
                <a href="http://droitauvelo.org/IMG/pdf/presentation_cyclabilite_v2_lille_180517_2.pdf" target="_blank">
                regardez cette présentation
                </a> afin de vous familliariser à ce concept de cycalbilité ainsi qu'à l'utilisation de la carte.
            </p>

            <p>
                Retrouvez plus d'information sur notre site internet : 
                <a href="https://droitauvelo.org/La-carte-de-cyclabilite-du-Nord-et-du-Pas-de-Calais" target="_blank">
                Droitauvelo.org section cartographie
                </a>
            </p>
        </div>
    </body>
</html>

app/cyclab/templates/cyclab/profiles.html
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
      integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
      crossorigin=""
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <title>{% trans "Profiles" %}</title>
  </head>
  <body>
    <div class="container subpages">
      <div class="inner-container">
          <h1 class="title">{% trans "Profiles" %}</h1>
          {% if not user.is_authenticated %}
          <a href="../" class="btn home-btn btn-center">{% trans "Return home" %}</a>
          <p class="login-message">{% trans "Login first to see your profiles" %}</p>
          {% endif %} {% if user.is_authenticated%}
          <form action="" method="POST">
            {% csrf_token %} {{ form }}
            <button type="submit" class="edit-btn">{% trans "Create new profile" %}</button>
          </form>

          <ul class="profile-list">
            {% for profile in profiles %}
            <div class="list-item">
              <li class="profile-label">
                <h3>{% trans "Profile" %}: {{ forloop.counter }}</h3>
                <p>{% trans "Type of rider" %}: {{ profile.get_rider_type_display }}</p>
                <p>{% trans "Speed" %}: {{ profile.get_rapidity_display}}</p>
                {% comment %}
                <a href="./{{ profile.id }}" class="edit-btn">{% trans "Edit profile" %}</a>
                {% endcomment %}
              </li>
            </div>
            {% endfor %}
          </ul>
          <button class="cancel-btn"><a href="../" class="menu-link home">{% trans "Cancel" %}</a></button>
        </div>
        {% endif %}
    </div>
  </body>
</html>